Added Categories & Parsing
bullhorn/invenias-api-docs pull request #6
Opened 2021-11-30 11:29 UTC by Invenias

- Updated Invenias by Bullhorn Logo to the refreshed version
- Updated Invenias by Bullhorn favicon to the refreshed version
- Improvements were made to overall readability.
- Reduced sentence lengths.
- Reduced the number of complex paragraphs.
- Reduced bad adverb usage.
- Improved sentence variety.
- Reduced the number of ‘sticky’ sentences.
- Added a new Category section named ‘Categories’.
- Added a new Parsing section names ‘Parsing’.

2021-11-30 17:17 UTC, AlexanderLea requested changes

2021-11-30 17:22 UTC, Invenias commented on source/layouts/layout.erb
> +	<link rel="icon" type="image/x-icon" href="hhttps://www.invenias.com/wp-content/uploads/2021/10/cropped-invenias-32x32.png">
Fixed.

2021-11-30 17:23 UTC, Invenias commented on source/index.html.md
> +id_token | Also referred to as a ‘token hint' the id_token can be used to end a user session and revoking the current access_token.
Fixed

2021-11-30 17:23 UTC, Invenias commented on source/index.html.md
> +Please note, for each item where there is ‘null' data for a specified column, it will not return this column in the response to those items.
Fixed

2021-11-30 17:23 UTC, Invenias commented on source/index.html.md
> +The Invenias REST API has two endpoints available to help flag ‘People' and ‘Company' type entities that <i>may</i> already exist within the database. By utilizing these endpoints, it will help maint
Fixed

2021-12-01 10:04 UTC, AlexanderLea approved these changes

2021-12-01 10:04 UTC, merged